# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ms-configserver

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://everisbank.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_181ef4f11d45487a8b0a60d3018f2a14 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_9263e38637b84b94baee0518249f8ae6 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: everisbank.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_181ef4f11d45487a8b0a60d3018f2a14 }}/config-server:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ms-configserver'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_65c94aad29d64b37959fc0e2633e6289 }}
        images: 'everisbank.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_181ef4f11d45487a8b0a60d3018f2a14 }}/config-server:${{ github.sha }}'